### ISSUE TITLE
ValueError: Namespace AppIndicator3 not available

### ISSUE THREAD

**Issue by beucismis** [cadadr/pomodorino#41]
Distro: `Debian sid/unstable`
Python version: `3.9.2`
PIP version: `21.0.1`

If you are getting this error:

```bash
 $ pomodorino 
Traceback (most recent call last):
  File "/usr/bin/pomodorino", line 11, in <module>
    load_entry_point('pomodorino==0.1.1', 'console_scripts', 'pomodorino')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 474, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2846, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/pomodorino/__init__.py", line 19, in <module>
    from pomodorino import app
  File "/usr/lib/python3/dist-packages/pomodorino/app.py", line 33, in <module>
    from pomodorino.indicator import Indicator
  File "/usr/lib/python3/dist-packages/pomodorino/indicator.py", line 28, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

```

Try installing the Gir1.2-Appindicator3. I did work! :)

```bash
sudo apt install gir1.2-appindicator3-0.1
```

**Comment by cadadr** [comment]
Thanks for the report!

Did you install pomodorino with the released Debian package, or did you install it via pip?

**Comment by beucismis** [comment]
You're welcome. ...with the released Debian package.

**Comment by cadadr** [comment]
Just pushed a patch on branch `default` that should fix this. PyGObject seems to favour Ayatana AppIndicator3 library, so I added that as a dependency. Feel free to report here / reopen if the issue persists.
