### ISSUE TITLE
PKGBUILD missing libappindicator-gtk3

### ISSUE THREAD

**Issue by variadico** [cadadr/pomodorino#56]
Installed this way.
```
git clone https://aur.archlinux.org/pomodorino.git
cd pomodorino/
makepkg -sirc
```
```
$ git rev-parse HEAD
245171ccf03f6eba666638b1da4a85e286d23a8b
$ ls
Makefile  PKGBUILD  pomodorino-0.2.0a1-1-any.pkg.tar.zst  pomodorino-0.2.0a1.tar.gz
```

I tried to print the version, but it crashes.
```
$ pomodorino --version
Traceback (most recent call last):
  File "/usr/bin/pomodorino", line 33, in <module>
    sys.exit(load_entry_point('pomodorino==0.2.0a1', 'console_scripts', 'pomodorino')())
  File "/usr/bin/pomodorino", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/pomodorino/__init__.py", line 19, in <module>
    from pomodorino import app
  File "/usr/lib/python3.9/site-packages/pomodorino/app.py", line 33, in <module>
    from pomodorino.indicator import Indicator
  File "/usr/lib/python3.9/site-packages/pomodorino/indicator.py", line 28, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

**Comment by cadadr** [comment]
Thanks for the report!

Can you try installing `libappindicator-gtk3` and testing again? Looks like that's the missing dependency, if it solves the crash for you I'll add it to the PKGBUILD.

**Comment by variadico** [comment]
```
sudo pacman -S libappindicator-gtk3
```
Fixed the crash. 👍🏽

**Comment by cadadr** [comment]
Thanks for testing! I just updated the PKGBUILD. I'm closing this issue, but if for some reason the problem continues, feel free to open it again.
